name: Node.js CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout branch
        uses: actions/checkout@v3
      - name: setup node env
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: install packages
        run: npm ci
      - name: build
        run: npm run build --if-present
      - name: test
        run: npm test
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
