name: release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: '18.x'
          cache: npm
      - name: install packages
        run: npm ci
      - name: test
        run: npm test
      - name: build and zip lambdas
        run: npm run build
      - name: semantic release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
